site_name: straysheep.dev
#site_url: http://127.0.0.1:8000
site_url: https://straysheep-dev.github.io
repo_url: https://github.com/straysheep-dev/straysheep-dev.github.io
repo_name: straysheep-dev.github.io

theme:
  name: material

#  icon:
#    logo: material/sheep
  logo: assets/logo.svg
  favicon: assets/favicon.svg

  font:
    text: Roboto
    code: Roboto Mono

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep orange
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
#    - navigation.expand
    - navigation.path
    - navigation.top
    - toc.integrate
#    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.tooltips

plugins:
  - blog:
      blog_toc: true
      #archive: false
      archive_toc: true
      categories: false
      pagination_per_page: 100
  - search
  - social

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
  - footnotes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/straysheep-dev

# https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=nav#section-index-pages
nav:
  - Main: index.md
  - License: license.md
  - Blog:
    - blog/index.md
    - Post: blog/posts/resources.md
    - Post: blog/posts/aide.md
    - Post: blog/posts/art-x-uac.md
    - Post: blog/posts/bind9.md
    - Post: blog/posts/bitwarden.md
    - Post: blog/posts/check-auditd-demo.md
    - Post: blog/posts/cicd.md
    - Post: blog/posts/custom-shell-profiles.md
    - Post: blog/posts/flatpak.md
    - Post: blog/posts/kvm.md
    - Post: blog/posts/linting.md
    - Post: blog/posts/nzyme-rpi-proxmox-tailscale.md
    - Post: blog/posts/openscap.md
    - Post: blog/posts/openwrt.md
    - Post: blog/posts/pfsense.md
    - Post: blog/posts/powerstig.md
    - Post: blog/posts/proxmox.md
    - Post: blog/posts/rsync.md
    - Post: blog/posts/snap.md
    - Post: blog/posts/wazuh-tailscale.md
    - Post: blog/posts/windows.md



copyright: Copyright &copy; 2023-2024 straysheep-dev
